import type {
  Club,
  HomeStats,
  HomeToday,
  Interest,
  NexaEvent,
  Opportunity,
  University,
} from "./types";

const now = new Date();
const inDays = (d: number) => new Date(now.getTime() + d * 86_400_000).toISOString();

export const MOCK_INTERESTS: Interest[] = [
  { id: 1, name: "IT & Программчлал", slug: "it", icon: "💻" },
  { id: 2, name: "Санхүү", slug: "finance", icon: "💰" },
  { id: 3, name: "Дизайн", slug: "design", icon: "🎨" },
  { id: 4, name: "Маркетинг", slug: "marketing", icon: "📣" },
  { id: 5, name: "Хэл, Орчуулга", slug: "language", icon: "🌐" },
  { id: 6, name: "Спорт", slug: "sport", icon: "🏀" },
  { id: 7, name: "Эрдэм шинжилгээ", slug: "research", icon: "🔬" },
  { id: 8, name: "Сайн дурын ажил", slug: "volunteer", icon: "🤝" },
];

const interest = (slug: string) => MOCK_INTERESTS.find((i) => i.slug === slug)!;

export const MOCK_UNIVERSITIES: University[] = [
  {
    id: 1,
    slug: "num",
    name: "Монгол Улсын Их Сургууль",
    short_name: "МУИС",
    city: "Улаанбаатар",
    logo: null,
    cover_image: null,
    is_verified: true,
    is_launch_partner: true,
    founded_year: 1942,
  },
  {
    id: 2,
    slug: "must",
    name: "Шинжлэх Ухаан Технологийн Их Сургууль",
    short_name: "ШУТИС",
    city: "Улаанбаатар",
    logo: null,
    cover_image: null,
    is_verified: true,
    is_launch_partner: true,
    founded_year: 1969,
  },
  {
    id: 3,
    slug: "seic",
    name: "Санхүү Эдийн Засгийн Их Сургууль",
    short_name: "СЭЗИС",
    city: "Улаанбаатар",
    logo: null,
    cover_image: null,
    is_verified: true,
    is_launch_partner: true,
    founded_year: 1963,
  },
  {
    id: 4,
    slug: "mnums",
    name: "Анагаахын Шинжлэх Ухааны Үндэсний Их Сургууль",
    short_name: "АШУҮИС",
    city: "Улаанбаатар",
    logo: null,
    cover_image: null,
    is_verified: true,
    is_launch_partner: false,
    founded_year: 1961,
  },
];

const uni = (short: string) => MOCK_UNIVERSITIES.find((u) => u.short_name === short) ?? null;

export const MOCK_CLUBS: Club[] = [
  {
    id: 1,
    slug: "num-developers-club",
    name: "NUM Developers Club",
    logo: null,
    cover_image: null,
    university: uni("МУИС"),
    interests: [interest("it")],
    membership_type: "OPEN",
    member_count: 124,
  },
  {
    id: 2,
    slug: "hult-prize-ub",
    name: "HULT Prize UB",
    logo: null,
    cover_image: null,
    university: uni("ШУТИС"),
    interests: [interest("marketing")],
    membership_type: "REQUEST",
    member_count: 68,
  },
  {
    id: 3,
    slug: "finance-investment-club",
    name: "Finance & Investment Club",
    logo: null,
    cover_image: null,
    university: uni("СЭЗИС"),
    interests: [interest("finance")],
    membership_type: "OPEN",
    member_count: 91,
  },
  {
    id: 4,
    slug: "design-circle",
    name: "Design Circle",
    logo: null,
    cover_image: null,
    university: uni("МУИС"),
    interests: [interest("design")],
    membership_type: "OPEN",
    member_count: 57,
  },
  {
    id: 5,
    slug: "english-speaking-club",
    name: "English Speaking Club",
    logo: null,
    cover_image: null,
    university: uni("ШУТИС"),
    interests: [interest("language")],
    membership_type: "OPEN",
    member_count: 143,
  },
  {
    id: 6,
    slug: "volunteer-mongolia",
    name: "Volunteer Mongolia",
    logo: null,
    cover_image: null,
    university: null,
    interests: [interest("volunteer")],
    membership_type: "OPEN",
    member_count: 210,
  },
];

export const MOCK_OPPORTUNITIES: Opportunity[] = [
  {
    id: 1,
    slug: "frontend-developer-internship",
    type: "INTERNSHIP",
    type_display: "Дадлага",
    title: "Frontend Developer Internship",
    organization_name: "Khan Bank",
    cover_image: null,
    deadline: inDays(2),
    days_until_deadline: 2,
    is_deadline_soon: true,
    location: "Улаанбаатар",
    is_remote: false,
    audiences: ["UNIVERSITY"],
    is_paid: true,
    compensation: "900,000₮/сар",
    interests: [interest("it")],
    is_featured: true,
    verification_level: "OFFICIAL",
  },
  {
    id: 2,
    slug: "chevening-scholarship-2027",
    type: "SCHOLARSHIP",
    type_display: "Тэтгэлэг",
    title: "Chevening Scholarship 2027",
    organization_name: "UK Government",
    cover_image: null,
    deadline: inDays(25),
    days_until_deadline: 25,
    is_deadline_soon: false,
    location: "Их Британи",
    is_remote: false,
    audiences: ["UNIVERSITY", "WORKING"],
    is_paid: true,
    compensation: "Бүрэн санхүүжилттэй",
    interests: [interest("language")],
    is_featured: true,
    verification_level: "OFFICIAL",
  },
  {
    id: 3,
    slug: "hack-the-six-2027",
    type: "COMPETITION",
    type_display: "Тэмцээн",
    title: "Hack The Six 2027",
    organization_name: "NUM Developers Club",
    cover_image: null,
    deadline: inDays(10),
    days_until_deadline: 10,
    is_deadline_soon: false,
    location: "МУИС, IV байр",
    is_remote: false,
    audiences: ["UNIVERSITY"],
    is_paid: false,
    compensation: "",
    interests: [interest("it")],
    is_featured: true,
    verification_level: "OFFICIAL",
  },
  {
    id: 4,
    slug: "barista-oyutand-tohiromjtoi",
    type: "JOB",
    type_display: "Ажил",
    title: "Бариста — Оюутанд тохиромжтой",
    organization_name: "Blue Sky Coffee",
    cover_image: null,
    deadline: inDays(1),
    days_until_deadline: 1,
    is_deadline_soon: true,
    location: "Сүхбаатар дүүрэг",
    is_remote: false,
    audiences: ["SCHOOL", "UNIVERSITY"],
    is_paid: true,
    compensation: "8,000₮/цаг",
    interests: [interest("marketing")],
    is_featured: false,
    verification_level: "OFFICIAL",
  },
  {
    id: 5,
    slug: "junior-graphic-designer",
    type: "JOB",
    type_display: "Ажил",
    title: "Junior Graphic Designer",
    organization_name: "Adiya Creative Studio",
    cover_image: null,
    deadline: inDays(5),
    days_until_deadline: 5,
    is_deadline_soon: false,
    location: "Улаанбаатар",
    is_remote: false,
    audiences: ["UNIVERSITY", "WORKING"],
    is_paid: true,
    compensation: "1,100,000₮/сар",
    interests: [interest("design")],
    is_featured: true,
    verification_level: "OFFICIAL",
  },
  {
    id: 6,
    slug: "data-analytics-bootcamp",
    type: "COURSE",
    type_display: "Сургалт",
    title: "Data Analytics Bootcamp",
    organization_name: "Nexa Learning Partners",
    cover_image: null,
    deadline: inDays(8),
    days_until_deadline: 8,
    is_deadline_soon: false,
    location: "Онлайн",
    is_remote: true,
    audiences: ["UNIVERSITY", "WORKING"],
    is_paid: true,
    compensation: "Хөнгөлөлттэй 150,000₮",
    interests: [interest("it")],
    is_featured: false,
    verification_level: "OFFICIAL",
  },
];

export const MOCK_EVENTS: NexaEvent[] = [
  {
    id: 1,
    slug: "hack-the-six-opening",
    title: "Hack The Six 2027 — Opening Night",
    cover_image: null,
    start_at: inDays(3),
    end_at: inDays(3),
    location: "Улаанбаатар",
    is_online: false,
    interests: [interest("it")],
    university: uni("МУИС"),
    interested_count: 34,
  },
  {
    id: 2,
    slug: "hult-prize-info-session",
    title: "HULT Prize UB Info Session",
    cover_image: null,
    start_at: inDays(5),
    end_at: inDays(5),
    location: "Улаанбаатар",
    is_online: false,
    interests: [interest("marketing")],
    university: uni("ШУТИС"),
    interested_count: 19,
  },
  {
    id: 3,
    slug: "design-circle-portfolio-workshop",
    title: "Design Circle: Portfolio Workshop",
    cover_image: null,
    start_at: inDays(7),
    end_at: inDays(7),
    location: "Улаанбаатар",
    is_online: false,
    interests: [interest("design")],
    university: uni("МУИС"),
    interested_count: 27,
  },
];

export const MOCK_STATS: HomeStats = {
  opportunities: 120,
  universities: 12,
  clubs: 30,
  events: 50,
};

export const MOCK_TODAY: HomeToday = {
  as_of: now.toISOString(),
  deadline_soon: MOCK_OPPORTUNITIES.filter((o) => o.is_deadline_soon),
  upcoming_events: MOCK_EVENTS,
  featured: MOCK_OPPORTUNITIES.filter((o) => o.is_featured),
};

export function mockForAudience(audience: string): Opportunity[] {
  return MOCK_OPPORTUNITIES.filter(
    (o) => o.audiences.includes(audience as never) || o.audiences.includes("ALL")
  );
}
